### ISSUE TITLE
Allow negative #const values

### ISSUE THREAD

**Issue by HSZemi** [mangudai/vscode#3]
Negative values in #const declarations yield a linting error:

![grafik](https://user-images.githubusercontent.com/3027817/42413277-7af9573c-821d-11e8-82b3-e1e2dbf73a39.png)

They are however needed for [some special effects like custom regicide/treason](http://aok.heavengames.com/cgi-bin/forums/display.cgi?action=st&fn=4&tn=44466&st=0#post0) (see bottom of the post).

**Comment by deltaidea** [comment]
Right! I think I've fixed this already in the core library but haven't updated IDE packages. Thanks for pointing it out.

As a side note, the library itself is very much unfinished, with many false positives and breaking on edge cases. It'll get there.

**Comment by deltaidea** [comment]
Fixed in 0.3.3, please update the extension.
